In [34]:
import numpy
arr = numpy.array([1, 2, 3, 4, 6])
print(arr)

[1 2 3 4 6]


In [35]:
#create using tuple
arr = numpy.array((1, 2, 3, 4, 7))
print(type(arr))

<class 'numpy.ndarray'>


In [36]:
#2D array
arr = numpy.array([[1, 2,3], [3, 4, 5]])
print(arr[0][2])
print(arr[0, 2])

3
3


In [37]:
#3D array
arr = numpy.array([[[1, 2, 3], [4, 5, 6]], [[5, 6, 3], [4, 5, 9]]])
print(arr[1][0][2])

3


In [38]:
#gives dimension
print(arr.ndim)

#here comes the negativeindexing also, -1 means last element from last
print(arr[-1])

3
[[5 6 3]
 [4 5 9]]


In [39]:
#slicing like this [start:end:step]
#goes from start to end-1 index
arr = numpy.array([1, 2, 3, 4, 5, 6])
print(arr[0:4])

print(arr[3 :])

[1 2 3 4]
[4 5 6]


In [40]:
#negative slicing
#here if direction is important, default is left to right
print(arr[-3: -1])

#this will give empty bc direction is wrong
print(arr[-1: -3])

#in specified direction, last element won't be printed
print(arr[-1: -3 :-1])

[4 5]
[]
[6 5]


In [41]:
#Data type

print(arr.dtype)

arr = numpy.array([1.1, 2.1, 3.1])

#changing the datatype
arr = arr.astype('i')

print(arr)
print(arr.dtype)

int64
[1 2 3]
int32


In [48]:
#a copy and a view of an array is that the copy is a new array, 
#and the view is just a view of the original array.

x = arr.view()
y = arr.copy()

y = numpy.append(y, [5])
print(arr)
print(x)
print(y)



[1 2 3]
[1 2 3]
[1 2 3 5]


In [61]:
#The shape of an array is the number of elements in each dimension.
#it return the tuple of elements in each dimension
arr = numpy.array([[1, 3, 4], [1, 2, 3]])

#arr.shape return the view of the array
print(arr.shape)

(2, 3)


In [63]:
arr = numpy.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [66]:
#iterating to the arra
for x in arr:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [67]:
arr = numpy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in numpy.nditer(arr):
  print(x)

#there is function for iterating in numpy, nditer

1
2
3
4
5
6
7
8


In [68]:
for idx, x in numpy.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [77]:
arr1 = numpy.array([1, 2, 3, 3])
arr2 = numpy.array([4, 5, 6, 4])
arr3 = numpy.array([5, 6, 7, 9])

arr = numpy.concatenate((arr1, arr2))

print(arr)

arr = numpy.stack((arr1, arr2, arr3), axis=1)

print(arr)

[1 2 3 3 4 5 6 4]
[[1 4 5]
 [2 5 6]
 [3 6 7]
 [3 4 9]]


In [80]:
arr =  numpy.array([1, 2, 3, 4, 5])
newarr =  numpy.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5])]


In [81]:
arr =numpy.array([1, 2, 3, 4, 5, 4, 4])

#where x is the array containing indexes of maching query
x =numpy.where(arr == 4)
print(x)

#there is binary search is also there
#sort is also there

(array([3, 5, 6]),)


In [83]:
#filter same as js
arr = numpy.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
